### ISSUE TITLE
Java 11 support?

### ISSUE THREAD

**Issue by smortex** [samplerr/samplerr#16]
Updating a node from Debian Stretch to Buster (so going from Java 8 to Java 11), riemann was unable to start:

```
ERROR [2019-12-12 03:18:07,926] main - riemann.bin - Couldn't start
clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: No such namespace: samplerr, compiling:(/etc/riemann/riemann.config:43:24)
```

The error message seems samplerr-centric, I had no opportunity to dig in this problem deeper for now, and told the service to run wih the previous version of Java.  Opening this issue so we can keep a track of this and hopefully kick the root cause of the issue.

<details>
<summary>Backtrace</summary>

```
ERROR [2019-12-12 03:18:07,926] main - riemann.bin - Couldn't start
clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: No such namespace: samplerr, compiling:(/etc/riemann/riemann.config:43:24)
        at clojure.lang.Compiler.analyze(Compiler.java:6792)
        at clojure.lang.Compiler.analyze(Compiler.java:6729)
        at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3813)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:7005)
        at clojure.lang.Compiler.analyze(Compiler.java:6773)
        at clojure.lang.Compiler.access$300(Compiler.java:38)
        at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6368)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:7003)
        at clojure.lang.Compiler.analyze(Compiler.java:6773)
        at clojure.lang.Compiler.analyze(Compiler.java:6729)
        at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6100)
        at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5460)
        at clojure.lang.Compiler$FnExpr.parse(Compiler.java:4022)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:7001)
        at clojure.lang.Compiler.analyze(Compiler.java:6773)
        at clojure.lang.Compiler.eval(Compiler.java:7059)
        at clojure.lang.Compiler.load(Compiler.java:7514)
        at clojure.lang.Compiler.loadFile(Compiler.java:7452)
        at clojure.lang.RT$3.invoke(RT.java:325)
        at riemann.config$include.invokeStatic(config.clj:450)
        at riemann.config$include.invoke(config.clj:427)
        at riemann.bin$_main$fn__14138.invoke(bin.clj:139)
        at riemann.bin$run_app_BANG_.invokeStatic(bin.clj:123)
        at riemann.bin$run_app_BANG_.invoke(bin.clj:115)
        at riemann.bin$_main.invokeStatic(bin.clj:139)
        at riemann.bin$_main.doInvoke(bin.clj:127)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at riemann.bin.main(Unknown Source)
Caused by: java.lang.RuntimeException: No such namespace: samplerr
        at clojure.lang.Util.runtimeException(Util.java:221)
        at clojure.lang.Compiler.resolveIn(Compiler.java:7269)
        at clojure.lang.Compiler.resolve(Compiler.java:7243)
        at clojure.lang.Compiler.analyzeSymbol(Compiler.java:7204)
        at clojure.lang.Compiler.analyze(Compiler.java:6752)
        ... 29 common frames omitted
```
</details>

**Comment by smortex** [comment]
Hit this again today…

Adding the following riemann configuration seems to help:
```clojure
(require '[riemann.plugin.samplerr :as samplerr])
```

Maybe a bug for riemann itself?

**Comment by faxm0dem** [comment]
Maybe related to https://github.com/riemann/riemann/pull/951
