### ISSUE TITLE
Sort archives

### ISSUE THREAD

**Issue by samplerr** [samplerr/samplerr#2]
Archives should be sorted according to the retention policy so the user doesn't have to.
Otherwise `rotate` will misbehave

**Comment by faxm0dem** [comment]
Maybe this relates to the following: on month change, the rotation process fails on the second day.

**Comment by faxm0dem** [comment]
Here's the stack trace:

```
at clojure.core$ex_info.invokeStatic(core.clj:4617) at clojure.core$ex_info.invoke(core.clj:4617) at qbits.spandex$response_ex__GT_ex_info.invokeStatic(spandex.clj:218) at qbits.spandex$response_ex__GT_ex_info.invoke(spandex.clj:215) at qbits.spandex$eval6897$fn__6898.invoke(spandex.clj:227) at qbits.spandex$eval6880$fn__6881$G__6871__6886.invoke(spandex.clj:222) at qbits.spandex$default_exception_handler.invokeStatic(spandex.clj:238) at qbits.spandex$default_exception_handler.invoke(spandex.clj:231) at qbits.spandex$request.invokeStatic(spandex.clj:271) at qbits.spandex$request.invoke(spandex.clj:253) at riemann.plugin.samplerr$index_exists_QMARK_.invokeStatic(samplerr.clj:279) at riemann.plugin.samplerr$index_exists_QMARK_.invoke(samplerr.clj:276) at riemann.plugin.samplerr$shift_alias.invokeStatic(samplerr.clj:388) at riemann.plugin.samplerr$shift_alias.invoke(samplerr.clj:375) at riemann.plugin.samplerr$rotate.invokeStatic(samplerr.clj:454) at riemann.plugin.samplerr$rotate.invoke(samplerr.clj:447) at riemann.plugin.samplerr$rotation_service$rot__7675.invoke(samplerr.clj:470) at riemann.service.ThreadService$thread_service_runner__6478$fn__6479.invoke(service.clj:71) at riemann.service.ThreadService$thread_service_runner__6478.invoke(service.clj:70) at clojure.lang.AFn.run(AFn.java:22) at java.lang.Thread.run(Thread.java:748)
```

**Comment by faxm0dem** [comment]
Maybe related to: on month change, rotation aliases yearly indices to previous month's daily indices.
